/**
 * Type Definitions for enforcement Package
 * 
 * Auto-generated by typescript-remediation/generate-types.mjs
 * Date: 2026-02-17T23:50:28.144Z
 * 
 * ⚠️ WARNING: These are SCAFFOLDS only! Review and implement proper types.
 * 
 * TODO:
 * - Review each type and add proper structure
 * - Add JSDoc documentation
 * - Consider moving types to appropriate domain files
 * - Remove 'unknown' placeholders with real types
 */

// ============================================================================
// Core Types (alphabetical)
// ============================================================================


// ============================================================================
// Type Categories (for reference)
// ============================================================================
// 
// Metrics (0 types):

//
// Analysis (0 types):

//
// Configuration (0 types):

//
// Results (0 types):

//
// Strategy (0 types):

//
// Other (0 types):

