name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Install package with '...'
        2. Create file with '....'
        3. Run command '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the function to return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages, stack traces, etc.
      placeholder: |
        Error: Cannot read property 'foo' of undefined
        at Function.bar (/path/to/file.ts:123:45)
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Reproduction
      description: If possible, provide a minimal code sample that reproduces the issue.
      render: typescript
      placeholder: |
        import { MyClass } from '@dcyfr/package';
        
        const instance = new MyClass();
        instance.doSomething(); // Throws error here
    validations:
      required: false

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Which version of the package are you using?
      placeholder: "1.2.3"
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: Which version of Node.js are you using?
      options:
        - "20.x (LTS)"
        - "18.x (LTS)"
        - "22.x (Current)"
        - "16.x or earlier"
        - "Other (please specify in Additional Context)"
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Any other relevant environment information (TypeScript version, build tools, etc.)
      placeholder: |
        - TypeScript: 5.3.0
        - Build tool: Vite 5.0.0
        - Framework: Next.js 14.0.0 (if applicable)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, links, related issues, etc.)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information above
          required: true
        - label: I am using a supported version of Node.js (18.x or higher)
          required: false
        - label: I have tested with the latest version of the package
          required: false
